TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.1
  max_rotational_vel: 1.0
  min_in_place_rotational_vel: 0.3
  
  meter_scoring: true
  pdist_scale: 0.9
  gdist_scale: 0.6

  acc_lim_th: 1
  acc_lim_x: 1
  acc_lim_y: 1
  latch_xy_goal_tolerance: true
  xy_goal_tolerance: 0.30

  holonomic_robot: false
